g++ trialGas.cxx ../src/castGas.cxx ../src/castMagnet.cxx -I ../inc/ -o bin/trialGas
g++ trialMagnet.cxx ../src/castGas.cxx ../src/castMagnet.cxx -I ../inc/ -o bin/trialMagnet
g++ conversionProb.cxx ../src/castConversion.cxx ../src/castGas.cxx ../src/castMagnet.cxx -I ../inc/ -o bin/conversionProb
